[package]
name = "particle_life"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
egui-macroquad = "0.17.3"
macroquad = "0.4.14"
rand = "0.9.0"
rayon = "1.10.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
